"""Windows-local platform contracts for Townlight desktop deployments."""

from __future__ import annotations

from townlight_core.platform.backup import (
    BackupItem,
    BackupManifest,
    BackupRestoreAction,
    BackupRestorePlan,
    BackupValidationResult,
    build_backup_manifest,
    plan_restore,
    validate_backup_manifest,
)
from townlight_core.platform.health import (
    PlatformHealthCheck,
    PlatformHealthStatus,
    PlatformHealthSummary,
    summarize_platform_health,
)
from townlight_core.platform.modules import (
    WINDOWS_LOCAL_BLOCKED_RUNTIME_KINDS,
    ModuleBackupHook,
    ModuleDependency,
    ModuleHealthCheck,
    ModuleManifest,
    ModuleMigration,
    ModuleModelRequirement,
    ModulePermission,
    ModuleRegistryEntry,
    ModuleRegistryState,
    ModuleRoute,
    ModuleRuntimeRequirement,
    ModuleService,
    build_module_registry,
    validate_windows_local_manifest,
)
from townlight_core.platform.runtime import LocalRuntimeProfile, RuntimeActionResult
from townlight_core.platform.task_queue import (
    LocalTask,
    TaskHandler,
    claim_next_local_task,
    complete_local_task,
    enqueue_local_task,
    fail_local_task,
    run_one_local_task,
    task_row_to_envelope,
)
from townlight_core.platform.tasks import (
    LocalTaskEnvelope,
    LocalTaskResult,
    TaskQueueSummary,
    TaskRetryPolicy,
    can_run_task,
    next_retry_at,
    record_task_attempt,
    summarize_task_queue,
)

__all__ = [
    "BackupItem",
    "BackupManifest",
    "BackupRestoreAction",
    "BackupRestorePlan",
    "BackupValidationResult",
    "LocalRuntimeProfile",
    "LocalTask",
    "LocalTaskEnvelope",
    "LocalTaskResult",
    "ModuleBackupHook",
    "ModuleDependency",
    "ModuleHealthCheck",
    "ModuleManifest",
    "ModuleMigration",
    "ModuleModelRequirement",
    "ModulePermission",
    "ModuleRegistryEntry",
    "ModuleRegistryState",
    "ModuleRoute",
    "ModuleRuntimeRequirement",
    "ModuleService",
    "PlatformHealthCheck",
    "PlatformHealthStatus",
    "PlatformHealthSummary",
    "RuntimeActionResult",
    "TaskQueueSummary",
    "TaskHandler",
    "TaskRetryPolicy",
    "WINDOWS_LOCAL_BLOCKED_RUNTIME_KINDS",
    "build_backup_manifest",
    "build_module_registry",
    "can_run_task",
    "claim_next_local_task",
    "complete_local_task",
    "enqueue_local_task",
    "fail_local_task",
    "next_retry_at",
    "plan_restore",
    "record_task_attempt",
    "run_one_local_task",
    "summarize_platform_health",
    "summarize_task_queue",
    "task_row_to_envelope",
    "validate_backup_manifest",
    "validate_windows_local_manifest",
]
