"""Smoke tests for the shipped Townlight Core package-root surface."""

from __future__ import annotations


def test_v03_public_api_symbols_import_from_package_root() -> None:
    import townlight_core

    expected = {
        "AuditActor",
        "AuditEvent",
        "AuditHashChain",
        "AuditSubject",
        "PersistedAuditLogEntry",
        "ZERO_HASH",
        "canonical_audit_actor_id",
        "canonical_audit_details",
        "canonical_audit_timestamp",
        "compute_persisted_audit_hash",
        "verify_persisted_audit_chain",
        "SourceKind",
        "SourceReference",
        "CitationTarget",
        "DocumentMetadata",
        "ProvenanceBundle",
        "ConnectorImportError",
        "ImportManifest",
        "ExportManifest",
        "ImportedAgendaItem",
        "ImportedMeeting",
        "ManifestFile",
        "ManifestValidationError",
        "SUPPORTED_CONNECTORS",
        "DELTA_QUERY_PARAMS",
        "SyncCircuitPolicy",
        "SyncCircuitState",
        "SyncHealthStatus",
        "SyncOperatorStatus",
        "SyncRetryExhausted",
        "SyncRetryPolicy",
        "SyncRunResult",
        "SyncSourceStatus",
        "VendorDeltaRequestPlan",
        "apply_sync_run_result",
        "build_sync_operator_status",
        "build_sync_source_status",
        "compute_retry_delay",
        "compute_sync_health_status",
        "import_meeting_payload",
        "plan_vendor_delta_request",
        "validate_manifest",
        "with_http_retry",
        "BundleFile",
        "ExportBundle",
        "build_sha256sums",
        "validate_bundle",
        "write_manifest",
        "CitedSentence",
        "CitationValidationError",
        "DiscoveredRecord",
        "DeadlinePlan",
        "NoticeComplianceResult",
        "NoticeComplianceWarning",
        "SPECIAL_NOTICE_TYPES",
        "build_deadline_plan",
        "evaluate_notice_compliance",
        "CityProfile",
        "DepartmentProfile",
        "DeploymentProfile",
        "ModuleEnablement",
        "load_city_profile",
        "FetchedDocument",
        "HealthCheckResult",
        "HealthStatus",
        "OnboardingField",
        "OnboardingProgress",
        "DEFAULT_PROFILE_FIELDS",
        "completed_profile_fields",
        "compute_onboarding_status",
        "encrypt_json",
        "decrypt_json",
        "is_encrypted",
        "is_trusted_proxy_ip",
        "normalize_trusted_proxy_cidrs",
        "validate_url_host",
        "validate_odbc_connection_string",
        "next_profile_prompt",
        "parse_profile_answer",
        "SourceMaterial",
        "normalize_search_query",
        "normalize_search_text",
        "search_text_matches_query",
        "reciprocal_rank_fusion",
        "validate_cited_sentences",
        "normalized_text_sha256",
        "validate_release_browser_evidence",
        "BackupItem",
        "BackupManifest",
        "BackupRestoreAction",
        "BackupRestorePlan",
        "BackupValidationResult",
        "LocalRuntimeProfile",
        "LocalTask",
        "LocalTaskEnvelope",
        "LocalTaskResult",
        "ModuleBackupHook",
        "ModuleDependency",
        "ModuleHealthCheck",
        "ModuleManifest",
        "ModuleMigration",
        "ModuleModelRequirement",
        "ModulePermission",
        "ModuleRegistryEntry",
        "ModuleRegistryState",
        "ModuleRoute",
        "ModuleRuntimeRequirement",
        "ModuleService",
        "PlatformHealthCheck",
        "PlatformHealthStatus",
        "PlatformHealthSummary",
        "RuntimeActionResult",
        "TaskHandler",
        "TaskQueueSummary",
        "TaskRetryPolicy",
        "WINDOWS_LOCAL_BLOCKED_RUNTIME_KINDS",
        "build_backup_manifest",
        "build_module_registry",
        "can_run_task",
        "claim_next_local_task",
        "complete_local_task",
        "enqueue_local_task",
        "fail_local_task",
        "next_retry_at",
        "plan_restore",
        "record_task_attempt",
        "run_one_local_task",
        "summarize_platform_health",
        "summarize_task_queue",
        "task_row_to_envelope",
        "validate_backup_manifest",
        "validate_windows_local_manifest",
    }

    missing = expected - set(dir(townlight_core))
    assert not missing, f"Missing shipped public symbols: {missing}"


def test_v03_placeholder_modules_stay_out_of_root_surface() -> None:
    import townlight_core

    not_yet_shipped = {
        "Auth",
        "ExemptionRuleEngine",
    }

    assert not (not_yet_shipped & set(dir(townlight_core)))
